### ISSUE TITLE
Do you know any algorithm in Shell or Bash?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/shell#3]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Shell or Bash](https://github.com/AllAlgorithms/shell) this case

**Comment by Soumya44** [comment]
I am in.
